version: 2

sources:
    - name: datafeed_shared_schema
      database: "{{ ('ANAUM') }}"
      schema: raw_schema
      tables:
        - name: raw_customersdata
        - name: raw_ordersdata