version: 2

sources:
    - name: datafeed_shared_schema
      database: "{{ ('ANAUM') }}"
      schema: raw_schema
      tables:
        - name: raw_customersdata
          columns:
            - name: id
              tests:
                - unique
                - not_null
        - name: raw_ordersdata
        - name: stg_order
        - name: stg_product_name
